spring:
  application:
    #   项目应用名
    name: campus_health_service
  #   需要加载的配置文件
  profiles:
    active: datasource,cache
  freemarker:
    cache: false    #页面不加载缓存，修改即时生效
  http:
    enabled: true
    encoding:
      force: true
      charset: utf-8
      enabled: true
server:
  servlet:
    context-path: /campus
  port: 8021
  undertow:
    io-threads: 4
    worker-threads: 256
    buffer-size: 1024
    buffers-per-region: 1024
    direct-buffers: true

# 日志文件访问配置
logging:
  level:
    com.huiyi.campus.dao.mapper: debug
    com.huiyi.campus: debug
    root: info
  file: campus-health/logs/campus-info.log
  config: classpath:logback-spring.xml
#  minio对象存储配置
minio:
  endpoint: http://47.93.112.92:9000
  accessKey: admin
  secretKey: admin123456
  bucketImageName: campus



eureka:
  client:
    registryFetchIntervalSeconds: 5
    service-url:
      defaultZone: http://127.0.0.1:9003/eureka/
  instance:
    metadata-map:
      management:
        context-path: ${server.servlet.context-path}/actuator
    home-page-url: http://localhost:${server.port}/
    status-page-url: http://localhost:${server.port}/${server.servlet.context-path}/actuator/info
    leaseRenewalIntervalInSeconds: 10
    health-check-url-path: /actuator/health
    instance-id: ${spring.application.name}-${server.port}   #自定义服务名称
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    logfile:
      external-file: campus-health/logs/campus-info.log
    health:
      show-details: ALWAYS





