spring:
#  boot:
#    admin:
#      client:
#        url: http://localhost:9003/
#        instance:
#          service-url: http://47.93.112.92:${server.port}/${server.servlet.context-path}
#          prefer-ip: true
#          name: ${spring.application.name}
#          read-timeout: 10000

  application:
    #   项目应用名
    name: campus_health_service
  #   需要加载的配置文件
  profiles:
    active: datasource,cache
  freemarker:
    cache: false    #页面不加载缓存，修改即时生效
  http:
    enabled: true
    encoding:
      force: true
      charset: utf-8
      enabled: true
server:
  servlet:
    context-path: /campus
  port: 8021
  undertow:
    io-threads: 4
    worker-threads: 256
    buffer-size: 1024
    buffers-per-region: 1024
    direct-buffers: true

# 日志文件访问配置
logging:
  level:
    com.huiyi.campus.dao.mapper: debug
    com.huiyi.campus: debug
    root: info
  file: /opt/campus/health/campus-health/logs/campus-info.log
#  file: campus-health/logs/campus-info.log
  pattern: #日志高亮
    file: '%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%5p) %clr(${PID}){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n%wEx'
  config: classpath:logback-spring.xml
#  minio对象存储配置
minio:
  endpoint: http://47.93.112.92:9000
  accessKey: admin
  secretKey: admin123456
  bucketImageName: campus
  studentImage: studentImage


#项目健康监控
#management:
#  endpoints:
#    web:
#      exposure:
#        include: "*"
#  endpoint:
#    health:
#      show-details: ALWAYS

