#lobak日志记录
logging:
  level:
    root: info
  file: /opt/zhihui/campus/admin-server/campus-health/logs/campus-admin-server-info.log
#  file: campus-health/logs/campus-admin-server-info.log
  pattern: #日志高亮
    file: '%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%5p) %clr(${PID}){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n%wEx'
  config: classpath:logback-spring.xml

server:
  port: 9003

##暴露所有监控端点
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS #总是展示详情信息
