#lobak日志记录
logging:
  config: classpath:logback-spring.xml
  level:
    root: info
  file: campus-health/logs/campus-admin-server-info.log

server:
  port: 9003

##暴露所有监控端点
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS #总是展示详情信息
