server:
  port: 8769
#  注册服务名称
spring:
  application:
    name: campus-boot-admin-server
# 微服务注册
  cloud:
    nacos:
      discovery:
        #必须配置ip地址
        server-addr: 192.168.123.13:8848
        # 将自己的服务注册到注册中心
        register-enabled: true
      #        namespace:
      config:
        server-addr: 192.168.123.13:8848
        enabled: true
        file-extension: yaml
#开放端点用于SpringBoot Admin的监控
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
#lobak日志记录
logging:
  config: classpath:logback-spring.xml
  level:
    root: info
  file: logs/campus-info.log