###########################campus pro生产环境配置###############################
# 系统安全配置文件加密key
jasypt:
  encryptor:
    password: aztKpms@e7Dy9Fc#
spring:
  # MYSQL数据库驱动配置
  datasource:
    name: db
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://47.115.41.64:3306/campus_health?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8&autoReconnect=true&&zeroDateTimeBehavior=convertToNull&useSSL=true&allowMulQueries=true&&nullCatalogMeansCurrent=true&allowMultiQueries=true
    username: root
    password: ENC(ikT3m1vmolEaqq4DXKq4Jw==)
    driver-class-name: com.mysql.cj.jdbc.Driver
    minIdle: 5
    maxActive: 100
    initialSize: 10
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 50
    removeAbandoned: true
    filters: stat,wall # ,wall,log4j # 配置监控统计拦截的filters，去掉后监控界面sql 无法统计，'wall'用于防火墙
    connectionProperties:  druid.stat.mergeSql=false;druid.stat.slowSqlMillis=5000 # 通过connectProperties属 性来打开mergeSql功能；慢SQL记录
    useGlobalDataSourceStat: true # 合并多个DruidDataSource的监控数据
    stat-view-servlet.enabled: true #是否启用StatViewServlet（监控页面）默认值为false
    stat-view-servlet.login-username: admin #设置访问druid监控页的账号,默认没有
    stat-view-servlet.login-password: admin #设置访问druid监控页的密码,默认没有


#mybatis配置
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    mapper-locations: classpath*:mapper/*Mapper.xml
    type-aliases-package: com.huiyi.campus.dao.mapper
    mapperScanPackage: com.huiyi.campus.dao.mapper
    config-location: classpath:/mybatis-config.xml
splitOrgId:
  splitSQL: SELECT :str AS value_str FROM DUAL
  oneMax: 1
# PageHelper分页插件
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: false
  params: count=countSql

#
#  server:
#    port: 443
#    ssl:
#      key-store: classpath:4694046_devlis.huiyi.club.pfx
#      key-store-password: 18XoW9zS
#      key-store-type: PKCS12