spring:
  application:
#   项目应用名
    name: campus_health_service
#   需要加载的配置文件
  profiles:
    active: datasource,cache,bootstrap
#  servlet:
#   项目默认路径
    context-path: /campus

  freemarker:
    cache: false    #页面不加载缓存，修改即时生效
  http:
    encoding:
      force: true
      charset: utf-8
      enabled: true
server:
#  项目默认路径
  servlet:
    context-path: /campus
  port: 8021
  tomcat:
    uri-encoding: UTF-8
logging:
  level:
    com:
      huiyi:
        pacs: debug
  config: classpath:logback.xml
#  minio对象存储配置
minio:
  endpoint: http://47.93.112.92:9000
  accessKey: admin
  secretKey: admin123456
  bucketImageName: campus
#login:
#  count: 3 # 系统最多允许多少台设备登录同一账号
# PageHelper分页插件
#pagehelper:
#  helperDialect: mysql
#  reasonable: true
#  supportMethodsArguments: false
#  params: count=countSql