###########################campus pro生产环境配置###############################
# 系统安全配置文件加密key
jasypt:
  encryptor:
    password: aztKpms@e7Dy9Fc#
rsa:
  publicKey: MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCKB3cMcgcDw5BJsxtxttn6woZylj/iAV2X6tBe0B9Y2vYa3v4F7FydX8psORNSjYSgktCvWAb1Nz0oDBKMyIZC1yU5Flw96GiIlpzKCPmACi4fznyC8YZQJ+8TFoNgQsbHP3/L3e7hsw6vWKYFiE/bb1g7YcWdvEf6y+y+WhFK2QIDAQAB
  privateKey: MIICdwIBADANBgkqhkiG9w0BAQEFAASCAmEwggJdAgEAAoGBAIoHdwxyBwPDkEmzG3G22frChnKWP+IBXZfq0F7QH1ja9hre/gXsXJ1fymw5E1KNhKCS0K9YBvU3PSgMEozIhkLXJTkWXD3oaIiWnMoI+YAKLh/OfILxhlAn7xMWg2BCxsc/f8vd7uGzDq9YpgWIT9tvWDthxZ28R/rL7L5aEUrZAgMBAAECgYAG8i05gRt9QwAl1U+SP2NkzRk69visBOmS1Yw62TpanFo6K/KYlbZrbQCgxZaFVv3PntPFnyZqfKclNsZQM18eNwvTF3i/vcOij38wsW1vj2ry7lC+tU6y9QV/Cuid6eFFPlBR3ELHiVEg0AQdq3yPBUUDLSFxxHbr04sPuANTAQJBAMHXe3GSADviv+hXZ9izn2Q0FdL5rJFsv+EYid7jvh677PxsfgjAnZ3gDegZdqKAFBnvjAPeDENVOFRGaqYerPECQQC2SlCPiKIT9u7IhuHoYl21xbG0bwqwaGhmeRK7w5Yl9/sNFXbFwwHJD2qMk5GRVx0K43Me06CJ0Qx7xb5tshxpAkA5tufpS7hIHF5ZVlT0H58wnZV16KLp9cA3zC+YrqR30CpiigcIohkL3Z8mYRaCkbHqevlsWVu7XI9WAFVWusFxAkEAg2UHsp4y7Z8VOPd4iK+2ilpon/1WQBfSAOMObMcrSEz56dFp3lyUwd9Z1uBbkd6v8XRHO5YhZpWHoQPFIn662QJBAK3+icud0Kl/P34yiJAbR4ftjsllwbc3ep73bnWZuQIb6V8Ux4ERqSseWrJGHZZXkKQkU915GqXssc5ym/kak10=
aes:
  salt: www_huiyi_com_cn
user:
  administrator: admin
  defaultPwd: 123456

spring:
  # MYSQL数据库驱动配置
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://120.78.82.196:3309/campus_health?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8&autoReconnect=true&&zeroDateTimeBehavior=convertToNull&useSSL=true&allowMulQueries=true&&nullCatalogMeansCurrent=true&allowMultiQueries=true
    username: root
    password: zhihuiJcE10myj20r8Q
    driver-class-name: com.mysql.cj.jdbc.Driver
    minIdle: 5
    maxActive: 100
    initialSize: 10
    max-wait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 50
    # 要启用PSCache，必须配置大于0，当大于0时，poolPreparedStatements自动触发修改为true
    max-pool-prepared-statement-per-connection-size: 50
    #   removeAbandoned: false
    filters: stat,log4j   # 配置监控统计拦截的filters，去掉后监控界面sql 无法统计，'wall'用于防火墙
    connectionProperties: druid.stat.mergeSql=false;druid.stat.slowSqlMillis=5000 # 通过connectProperties属 性来打开mergeSql功能；慢SQL记录
    useGlobalDataSourceStat: true # 合并多个DruidDataSource的监控数据


#mybatis配置
mybatis-plus:
  configuration:
    #    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    mapper-locations: classpath*:mapper/*Mapper.xml
    type-aliases-package: com.huiyi.campus.dao.mapper
    mapperScanPackage: com.huiyi.campus.dao.mapper
    config-location: classpath:/mybatis-config.xml
    field-strategy: 0 #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
splitOrgId:
  splitSQL: SELECT :str AS value_str FROM DUAL
  oneMax: 1
# PageHelper分页插件
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: false
  params: count=countSql
#
#  server:
#    port: 443
#    ssl:
#      key-store: classpath:4694046_devlis.huiyi.club.pfx
#      key-store-password: 18XoW9zS
#      key-store-type: PKCS12