spring:
  redis:
    host: 127.0.0.1
    port: 6370
    passwordEncrypt: false
    passwordEncryptMode: AES
    password: ENC(ikT3m1vmolEaqq4DXKq4Jw==)
    timeout: 30000
    jedis:
      pool:
        # 连接池最大连接数（使用负值表示没有限制）
        max-total: 1024
        # 连接池中的最大空闲连接
        max-idle: 200
        # 连接池中的最小空闲连接
        min-idle: 50
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: 3000
        # 初始化验证连接
        testOnBorrow: true
    database: 0